### ISSUE TITLE
New Request

### ISSUE THREAD

**Issue by madgocrazy** [smithcbp/Powershell-System-Info#1]
Hi There,

Thank you for developing such a useful tool.

Is there a way to add team viewer password on the front GUI ? 

Regards,
Anil Chauhan

**Comment by Sup3rlativ3** [comment]
No. The password is encrypted using AES. You can view the encrypted password at HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\TeamViewer\PermanentPassword
